apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  # storageClassName: do-block-storage
  volumeMode: Filesystem
status:
  phase: Pending
