---
apiVersion: v1
kind: Service
metadata:
  name: mutatepvc
  labels:
    app: mutatepvc
spec:
  publishNotReadyAddresses: true
  ports:
    - port: 443
      targetPort: 8443
  selector:
    app: mutatepvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutatepvc
  labels:
    app: mutatepvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mutatepvc
  template:
    metadata:
      name: mutatepvc
      labels:
        app: mutatepvc
    spec:
      containers:
        - name: mutator
          image: danielfbm/k8s-mutate-webhook:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 64Mi

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutatepvc
  labels:
    app: mutatepvc
webhooks:
  - name: mutatepvc.default.svc.cluster.local
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURXekNDQWtPZ0F3SUJBZ0lRQ2N3eXkrNk5tVXBZNTBkTnNEMHlJVEFOQmdrcWhraUc5dzBCQVFzRkFEQVYKTVJNd0VRWURWUVFERXdwcmRXSmxjbTVsZEdWek1CNFhEVEl3TVRBeU1EQTVNekl4TmxvWERUSXhNVEF5TURBNQpNekl4Tmxvd0lERWVNQndHQTFVRUF4TVZiWFYwWVhSbGNIWmpMbVJsWm1GMWJIUXVjM1pqTUlJQklqQU5CZ2txCmhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBbmI5UWF4OXRyVTYyeThyZ0UyaS9lNE9wRmFSNzlFUzkKNXJWdXd1STVwekY5UElCT09NWHptMVM4bXVhb2Z5enF2ckhFM2FuSTdmcGpmdzlJTlNoZEEvL1VNVWttVTZFVAphV3YrOWhPR1VHRk5UZWRQTW5vVHhDRTkwaWMweS9KdTNoa3JzaVZwU2M1YVN3SzF2cXR3dUJJZHU4S1ZnUlcvCkdPb2dRc2huVjdtV3NlR0VGU1lTRWhPOEVSc3lHaGI2ek5teUc1dzZuc09FLzdnT2Zwd2toVWxWVGh3TWk5eDIKWWp3cCtWT2pDR2hlWGhDY2x3YTlNN0hvbHZqb1JBZmFnNUxUSVRrcURtalcxQkM0cnNhMXZId2hMQXFsOWxNMgo4L3JUSDlkTzBUcVVtVjE3dGpnSUZ2b25VREtyMFM5Y2toZi9ZczUvdzlUOFVZVVJtcFEvL3dJREFRQUJvNEdiCk1JR1lNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBVEFNQmdOVkhSTUIKQWY4RUFqQUFNR01HQTFVZEVRUmNNRnFDQ1cxMWRHRjBaWEIyWTRJUmJYVjBZWFJsY0haakxtUmxabUYxYkhTQwpGVzExZEdGMFpYQjJZeTVrWldaaGRXeDBMbk4yWTRJamJYVjBZWFJsY0haakxtUmxabUYxYkhRdWMzWmpMbU5zCmRYTjBaWEl1Ykc5allXd3dEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSzduMFZRdlM5QStmdTRIeWdZNmpRaHYKaUsrZXpOSW9vUHg0eEtCTUVsVGpESC9KeWorVzE3MnRzT3ZzeGNBM1VzRGI5TW1XSURDSU15NHJIVGhJeFlhRgphVFBSZlVLRS95TFJhdklWQ3ArSk1GM0JJbUhQZ09sbFZJYW9FVEVZeUxQbUhPc213NTVRWEE2Z2hGTHN3eE1YCldPT2xUT1ZhblFzN0F6T25NVzVhTExlQ25pK3FnY28vNFR0eDdTVmZjbjV6dE52WWVhYnRFSjVlY0lkbUFqUFcKTm82UmdFam9PUU5QK2tRbGlHMWtibzZVWlRpdVZ6SmFoeU1OT3FJdjhSVmw0TlhocXBZeXZwQjlpQ1djcThzQgpmdmtmb29IbHZTUk5DZFNlTzRxajE5NS9LcVJTREY3b3llMFJ3Z3V1aXZNV1htZEZOV1pPdlpvZHZQM2hsTUk9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: mutatepvc
        namespace: default
        path: "/mutate"
        port: 443
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["persistentvolumeclaims"]
    sideEffects: None
    timeoutSeconds: 5
    reinvocationPolicy: Never
    failurePolicy: Ignore
    namespaceSelector:
      matchLabels:
        mutatepvc: enabled
